name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout into this repo source
      uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.2'

    - name: Install python requirements
      run: |
        pip install pyrogram tgcrypto

    - name: Clone VHSCode-Android source
      run: |
        git clone https://github.com/vhqtvn/VHSCode-Android source

    - name: Install ndk
      run: |
        sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147"

    - name: Build the app
      run: |
        cd source
        USE_SPLITBUILD=1 ./gradlew assembleRelease --no-daemon

    - name: Save revision and branch
      run: |
        echo "::set-env name=SHORT_REV::$(git rev-parse --short HEAD)"
        echo "::set-env name=LONG_REV::$(git rev-parse HEAD)"
        echo "::set-env name=BRANCH::$(sed 's/-/_/g' <<< `git rev-parse --abbrev-ref HEAD`)"

    - name: Set file name
      run: |
        echo "::set-env name=FILENAME4::VHSCode_${SHORT_REV}_arm64-v8a.apk"
        echo "::set-env name=FILENAME3::VHSCode_${SHORT_REV}_armeabi-v7a.apk"
        echo "::set-env name=FILENAME2::VHSCode_${SHORT_REV}_x86_64.apk"
        echo "::set-env name=FILENAME1::VHSCode_${SHORT_REV}_x86.apk"

    - run: ls -Ralph source/app/build/outputs/

    - name: Rename the app
      run: |
        mv source/app/build/outputs/apk/release/app-x86-release.apk ${FILENAME1}
        mv source/app/build/outputs/apk/release/app-x86_64-release.apk ${FILENAME2}
        mv source/app/build/outputs/apk/release/app-armeabi-v7a-release.apk ${FILENAME3}
        mv source/app/build/outputs/apk/release/app-arm64-v8a-release.apk ${FILENAME4}

    - name: Run android.py
      env:
        CHAT_ID: ${{ secrets.CHAT_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
      run: |
        python .github/workflows/android.py
